import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, useColorScheme, View } from 'react-native';
import { AppHeader } from '@/components/ui/app-header';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/empty-state';
import { FormInput } from '@/components/ui/form-input';
import { LoadingState } from '@/components/ui/loading-state';
import { ScreenScaffold } from '@/components/ui/screen-scaffold';
import { createFollowUp, completeFollowUp, fetchMyFollowUps, FollowUpView, rescheduleFollowUp, SalesRepFollowUp } from '@/services/follow-up-service';
import { showErrorMessage, showSuccessMessage } from '@/services/native-feedback-service';
import { semanticColors, spacing, typography } from '@/shared/theme';

const views: FollowUpView[] = ['today', 'upcoming', 'overdue'];
const label = (value: string) => value.split('_').map((word) => word[0]?.toUpperCase() + word.slice(1)).join(' ');
const localDateTime = (value: string) => { const date = new Date(value); return { date: date.toISOString().slice(0, 10), time: date.toTimeString().slice(0, 5) }; };
const iso = (date: string, time: string) => new Date(`${date}T${time || '09:00'}:00`).toISOString();

export default function FollowUpsScreen() {
  const params = useLocalSearchParams<{ customerId?: string; customerName?: string }>();
  const colors = semanticColors[useColorScheme() === 'dark' ? 'dark' : 'light'];
  const [view, setView] = useState<FollowUpView>('today'); const [items, setItems] = useState<SalesRepFollowUp[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [modal, setModal] = useState<'create' | 'complete' | 'reschedule' | null>(params.customerId ? 'create' : null); const [selected, setSelected] = useState<SalesRepFollowUp | null>(null);
  const now = localDateTime(new Date().toISOString()); const [dueDate, setDueDate] = useState(now.date); const [dueTime, setDueTime] = useState('09:00'); const [purpose, setPurpose] = useState(''); const [note, setNote] = useState(''); const [outcome, setOutcome] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); const result = await fetchMyFollowUps(view); if (result.success) { setItems(result.items); setError(null); } else setError(result.error); setLoading(false); }, [view]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const openCreate = () => { if (!params.customerId) { showErrorMessage('Open a customer record first to create a follow-up.', 'Select customer'); return; } setModal('create'); };
  const save = async () => { setSaving(true); let result: { success: boolean; error?: string }; if (modal === 'create' && params.customerId) result = await createFollowUp(params.customerId, iso(dueDate, dueTime), purpose, note); else if (modal === 'complete' && selected) result = await completeFollowUp(selected.id, outcome); else if (modal === 'reschedule' && selected) result = await rescheduleFollowUp(selected.id, iso(dueDate, dueTime)); else { setSaving(false); return; } setSaving(false); if (!result.success) { showErrorMessage(result.error ?? 'Unable to save follow-up.', 'Follow-up'); return; } setModal(null); setSelected(null); setPurpose(''); setNote(''); setOutcome(''); showSuccessMessage('Follow-up saved'); void load(); };
  const openReschedule = (item: SalesRepFollowUp) => { const next = localDateTime(item.dueAt); setSelected(item); setDueDate(next.date); setDueTime(next.time); setModal('reschedule'); };
  if (loading) return <ScreenScaffold header={<AppHeader title="Follow-Ups" subtitle="Customer follow-up" />}><LoadingState message="Loading follow-ups..." /></ScreenScaffold>;
  return <ScreenScaffold mode="scroll" header={<AppHeader title="Follow-Ups" subtitle="Customer follow-up" />}><View style={styles.container}>
    <View style={styles.tabs}>{views.map((item) => <Pressable key={item} onPress={() => setView(item)} style={[styles.tab, { borderColor: colors.border, backgroundColor: view === item ? colors.primary : colors.surface }]}><Text style={[styles.tabText, { color: view === item ? colors.onPrimary : colors.text }]}>{label(item)}</Text></Pressable>)}</View>
    {params.customerName ? <View style={[styles.customerContext, { borderColor: colors.border }]}><Text style={[styles.contextText, { color: colors.text }]}>New follow-up for {params.customerName}</Text><Button title="Add Follow-Up" onPress={openCreate} /></View> : null}
    {error ? <EmptyState title="Unable to load follow-ups" message={error} action={<Button title="Try Again" onPress={() => void load()} />} /> : items.length === 0 ? <EmptyState title={`No ${label(view).toLowerCase()} follow-ups`} message="Follow-ups created from a customer record will appear here." action={params.customerId ? <Button title="Add Follow-Up" onPress={openCreate} /> : undefined} /> : items.map((item) => <View key={item.id} style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.customer, { color: colors.text }]}>{item.customerName}</Text><Text style={[styles.copy, { color: colors.text }]}>{item.purpose}</Text><Text style={[styles.meta, { color: colors.textMuted }]}>{new Date(item.dueAt).toLocaleString()} · {label(item.status)}</Text>{item.note ? <Text style={[styles.meta, { color: colors.textMuted }]}>{item.note}</Text> : null}<View style={styles.actions}><Button title="Complete" variant="secondary" onPress={() => { setSelected(item); setOutcome(''); setModal('complete'); }} /><Button title="Reschedule" variant="outline" onPress={() => openReschedule(item)} /></View></View>)}
    <Modal visible={modal !== null} transparent animationType="slide" onRequestClose={() => setModal(null)}><View style={styles.overlay}><View style={[styles.modal, { backgroundColor: colors.surface }]}><Text style={[styles.modalTitle, { color: colors.text }]}>{modal === 'create' ? 'New Follow-Up' : modal === 'complete' ? 'Complete Follow-Up' : 'Reschedule Follow-Up'}</Text>{modal === 'create' ? <><Text style={[styles.meta, { color: colors.textMuted }]}>{params.customerName}</Text><FormInput label="Purpose *" value={purpose} onChangeText={setPurpose} placeholder="e.g. Confirm pickup timing" /><FormInput label="Note (Optional)" value={note} onChangeText={setNote} multiline numberOfLines={3} /></> : modal === 'complete' ? <FormInput label="Completion Outcome (Optional)" value={outcome} onChangeText={setOutcome} multiline numberOfLines={3} placeholder="Outcome or next context" /> : null}{modal !== 'complete' ? <><FormInput label="Due Date * (YYYY-MM-DD)" value={dueDate} onChangeText={setDueDate} /><FormInput label="Due Time * (HH:MM)" value={dueTime} onChangeText={setDueTime} /></> : null}<View style={styles.actions}><Button title="Cancel" variant="outline" onPress={() => setModal(null)} /><Button title={modal === 'complete' ? 'Complete' : modal === 'reschedule' ? 'Reschedule' : 'Create'} loading={saving} disabled={saving || (modal === 'create' && !purpose.trim())} onPress={() => void save()} /></View></View></View></Modal>
  </View></ScreenScaffold>;
}
const styles = StyleSheet.create({ container: { gap: spacing.md }, tabs: { flexDirection: 'row', gap: spacing.xs }, tab: { flex: 1, borderWidth: 1, borderRadius: 10, paddingVertical: spacing.sm, alignItems: 'center' }, tabText: { fontFamily: typography.fontFamily.bodySemibold, fontSize: typography.fontSize.xs }, customerContext: { borderWidth: 1, borderRadius: 10, padding: spacing.sm, gap: spacing.sm }, contextText: { fontFamily: typography.fontFamily.bodyMedium, fontSize: typography.fontSize.sm }, row: { borderWidth: 1, borderRadius: 12, padding: spacing.md, gap: spacing.xs }, customer: { fontFamily: typography.fontFamily.headingSemibold, fontSize: typography.fontSize.md }, copy: { fontFamily: typography.fontFamily.bodyMedium, fontSize: typography.fontSize.sm }, meta: { fontFamily: typography.fontFamily.body, fontSize: typography.fontSize.xs, lineHeight: 17 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.xs }, overlay: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.45)', padding: spacing.md }, modal: { borderRadius: 14, padding: spacing.md, gap: spacing.sm }, modalTitle: { fontFamily: typography.fontFamily.heading, fontSize: typography.fontSize.lg } });
